version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:20
    steps:
      - checkout
      - run:
          name: Install dependencies and build project
          command: npm install
          name: Test
          command: npm test
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud